### ISSUE TITLE
pywebview 2

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#197]
It is time for a new release. Let's call it 2.0 due the sheer amount of changes.

In addition to the merged features, I would like to include 
- [x] #181. Will start working on this soon
- [x] #122 would be nice too, at least with partial support. 
- [x] #153 Windows poses some problems. I will try to investigate whether it can be done with a reasonable effort. I don't have a working Windows environment at the moment though, so this might be postponed.

setup.py also needs to be updated to include the Windows dll.

**Comment by tjohnsonhvac** [comment]
Me likey!! if you want any help with anything let me know.

**Comment by r0x0r** [comment]
Help is most welcomed. There are two things that could be tackled at this
point
- Getting webbrowserinterop.dll into setup.py
- Windows support in #153. It will likely require COM code that would be
served via webbrowserinterop.dll. In other words this requires some C#/COM
knowledge.

**Comment by shivaprsdv** [comment]
We may also need #189: mark Qt4 as deprecated.

**Comment by r0x0r** [comment]
I have updated setup.py so that it works on Windows as well. Another thing I realized that the dll loading mechanism should be updated to work in a frozen environment

**Comment by shivaprsdv** [comment]
Check in: what about #177? Should be included in 2.0? (I think not, read my
comment there).

**Comment by r0x0r** [comment]
No, there are too many unknowns at this point.

**Comment by r0x0r** [comment]
Changelog for 2.0 can be found in the `pywebview2` branch

**Comment by shivaprsdv** [comment]
Changelog & Readme: need to update debug feature info.

**Comment by r0x0r** [comment]
I would like to resolve #211 and then we are good to go.

**Comment by r0x0r** [comment]
Done. 🍾
