### ISSUE TITLE
pywebview 3.0

### ISSUE THREAD

**Issue by r0x0r** [r0x0r/pywebview#318]
Will be the next version of _pywebview_. This will be the first _pywebview_ release introducing breaking API changes. The release will feature at least the following issues and features.

- [x] New API #272 
- [x] Page events #201
- [x] Edge support for Windows #243 
- [x] `get_element` function #292 
- [x] CSRF token #316 
- [x] (maybe) HTTP server #260 

Introducing the new API has the highest priority, due the sheer number of changes. All other work is to be done after the API is refactored. As always help is most appreciated.

**Comment by Herd25** [comment]
i'cam open video tag elements error from webkit resources

**Comment by sgroening** [comment]
An option to center a window on screen would be fantastic, though I'm by no means able to say what it'd take to realise in respect to the project being multi platform...

**Comment by r0x0r** [comment]
@sgroening @Herd25 
The best way to see your issue implemented, is to do it yourself.
At very least, create a separate issue ticket describing it in details.

**Comment by KilliKrate** [comment]
HTTP Server is a very nice idea, and is essentially the only way to serve local files on CEF

**Comment by r0x0r** [comment]
@KilliKrate you can serve local files using base uri approach. _pywebview_ sets a base uri automatically for local (protocolless) urls. See `todos` app for an example.

**Comment by r0x0r** [comment]
All pieces are now in place. Some testing and test fixes and version 3.0 is good to go.

**Comment by r0x0r** [comment]
I have created a [PR](https://github.com/r0x0r/pywebview/pull/340). Will keep it open till I get back from a festival. Comments and improvements are welcomed.

**Comment by r0x0r** [comment]
3.0 is released.
